# nixpacks.toml

[phases.setup]
# Bu satır, Nixpacks'e Mayıs 2024'ten (veya daha yeni) bir paket seti kullanmasını söyler
nixpkgsArchive = "nixos-24.05" 

# Bu da artık 'dart-sdk' paketinin modern bir sürümünü kuracaktır
nixPkgs = ["dart-sdk"]